services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    ports:
      - "80:80"

  db:
    build: ./mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql_data:/var/lib/mysql

  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    container_name: git-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git
